version: "3"
services:
  l4d2server:
    container_name: l4d2server
    # 使用本地构建或在线镜像
    image: ghcr.io/ahdg6/l4d2server:latest
    # build:
      # context: .
      # dockerfile: Dockerfile
      # args:
        # STEAM_USERNAME_ARG: ${STEAM_USERNAME}
        # STEAM_PASSWORD_ARG: ${STEAM_PASSWORD}
    ports:
      - "27015:27015"
      - "27015:27015/udp"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/addons/:/home/steam/l4d2server/left4dead2/addons/
      - ./data/cfg/server.cfg:/home/steam/l4d2server/left4dead2/cfg/server.cfg:ro
      - ./data/cfg/:/home/steam/l4d2server/left4dead2/cfg/
      - ./data/host.txt:/home/steam/l4d2server/left4dead2/host.txt:ro
      - ./data/motd.txt:/home/steam/l4d2server/left4dead2/motd.txt:ro
      - ./plugins:/plugins
    command: "-secure +exec server.cfg +map c1m1_hotel -port 37015 -tickrate 96"
