version: "3"
services:
  l4d2server:
    container_name: l4d2server
    # 使用本地构建或在线镜像
    # image: ghcr.io/ahdg6/l4d2server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # 本地构建时通过环境变量（或 .env 文件）传入
        STEAM_USERNAME_ARG: ${STEAM_USERNAME}
        STEAM_PASSWORD_ARG: ${STEAM_PASSWORD}
    ports:
      - "27015:27015"
      - "27015:27015/udp"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./data/addons/:/home/steam/l4d2server/left4dead2/addons/
      - ./data/cfg/:/home/steam/l4d2server/left4dead2/cfg/
      - ./data/host.txt:/home/steam/l4d2server/left4dead2/host.txt:ro
      - ./data/motd.txt:/home/steam/l4d2server/left4dead2/motd.txt:ro
      - ./plugins:/plugins
    command: [
      "-insecure",
      "+hostport", "27015",
      "+condebug",
      "+exec", "server.cfg",
      "-nomaster",
      "+map", "c1m2_streets",
      "-tickrate", "96"
    ]
