name: Build
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/l4d2server
          tags: |
            type=edge,branch=main
            type=ref,event=pr
            type=ref,event=tag
            type=raw,value=latest
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          secrets: |
            STEAM_USERNAME=${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD=${{ secrets.STEAM_PASSWORD }}
          tags: ${{ steps.meta.outputs.tags }}
